### ISSUE TITLE
Simple application causes reflect panic

### ISSUE THREAD

**Issue by sewnie** [diamondburned/gotk4-adwaita#11]
```go
package main

import (
        "os"

        "github.com/diamondburned/gotk4/pkg/gio/v2"
        "github.com/diamondburned/gotk4/pkg/gtk/v4"
        "github.com/diamondburned/gotk4-adwaita/pkg/adw"
)

func main() {
        app := adw.NewApplication("com.github.diamondburned.gotk4-examples.gtk4.simple", gio.ApplicationFlagsNone)
        app.Connect("activate", activate)

        if code := app.Run(os.Args); code > 0 {
                os.Exit(code)
        }
}

func activate(app *gtk.Application) {
        window := adw.NewApplicationWindow(app)
        window.Show()
}
```
```
panic: reflect: Call with too few input arguments [recovered]
        panic: closure error: unexpected panic caught: reflect: Call with too few input arguments

Closure added at:
        main.main at /home/meow/src/test/main.go:13
        runtime.main at /usr/lib/go/src/runtime/proc.go:267
        runtime.goexit at /usr/lib/go/src/runtime/asm_amd64.s:1650

goroutine 1 [running, locked to thread]:
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).Panicf(0xc0000aa300, {0xa9dd4b, 0x1b}, {0xc00013b148, 0x1, 0x1})
        /home/meow/.cache/go/mod/github.com/diamondburned/gotk4/pkg@v0.0.6-0.20231227124334-d08a1ac493a4/core/closure/funcstack.go:104 +0x928
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0xaab7d8?)
        /home/meow/.cache/go/mod/github.com/diamondburned/gotk4/pkg@v0.0.6-0.20231227124334-d08a1ac493a4/core/closure/funcstack.go:122 +0xc5
panic({0x87fa40?, 0xafeb80?})
        /usr/lib/go/src/runtime/panic.go:914 +0x21f
reflect.Value.call({0x881400?, 0xaa9920?, 0x858d5b?}, {0xa957a5, 0x4}, {0xc000152510, 0x0, 0x0?})
        /usr/lib/go/src/reflect/value.go:439 +0x1c65
reflect.Value.Call({0x881400?, 0xaa9920?, 0x9f1ee0?}, {0xc000152510?, 0xaabd05?, 0x0?})
        /usr/lib/go/src/reflect/value.go:380 +0xb9
github.com/diamondburned/gotk4/pkg/core/glib._gotk4_goMarshal(0x7f116602f2f0, 0x0, 0x1, 0x7fff8188db20, 0x4f6785?, 0x7f116602a260)
        /home/meow/.cache/go/mod/github.com/diamondburned/gotk4/pkg@v0.0.6-0.20231227124334-d08a1ac493a4/core/glib/glib.go:294 +0x9a5
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x7f116602a260, 0x1, 0x7f11adae0750)
        _cgo_gotypes.go:13789 +0x4b
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0xc00013dbe0?, 0xc?, 0x7f11adae0750?)
        /home/meow/.cache/go/mod/github.com/diamondburned/gotk4/pkg@v0.0.6-0.20231227124334-d08a1ac493a4/gio/v2/gio.go:41611 +0x67
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc0001524f8, {0xc000016060?, 0x1, 0x1})
        /home/meow/.cache/go/mod/github.com/diamondburned/gotk4/pkg@v0.0.6-0.20231227124334-d08a1ac493a4/gio/v2/gio.go:41611 +0x20b
main.main()
        /home/meow/src/test/main.go:15 +0x70
```
https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/initialization.html
> Using AdwApplication (Recommended)

**Comment by diamondburned** [comment]
Try doing 

```go
app.ConnectActivate(func() { activate(app) })
```

**Comment by sewnie** [comment]
`./main.go:13:40: cannot use app (variable of type *adw.Application) as *gtk.Application value in argument to activate`

edit: using
`app.ConnectActivate(func() { activate(&app.Application) })`
fixed it

**Comment by sewnie** [comment]
![20231230_091917](https://github.com/diamondburned/gotk4-adwaita/assets/47404953/fc865546-7f47-4a47-a9a6-ac4a62b89621)
Whats with this weird border present in gotk4-adwaita btw? Top is a C equivalent.

**Comment by sewnie** [comment]
Today i learned simply adding `adw.Init()` to activate simply makes it easier and so i can use gotkit. awesome
